### ISSUE TITLE
Additional attributes doesn't require values

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#514] opened 2019-06-06 09:49 UTC
- When setting additional attributes, values aren't required.

- If they aren't provided then this attribute is not set:

  ```js
  // output
  { variable: 'foo' }
  
  // should be
  { variable: 'foo', value: ? }
  ```

- Additionally, when changing variable, value is not reset.

**Comment by wwqrd** [comment] 2019-06-06 10:34
In attributes table, boolean inputs should use a toggle (so that they default to _false_)

**Comment by jthrilly** [comment] 2019-06-06 10:45
duplicate of #513

**Closed** 2019-06-06 10:52 UTC
