### ISSUE TITLE
App crash when changing node type

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#656] opened 2020-06-30 12:48 UTC
When attempting to change the node type, I got an app crash:

<img width="1552" alt="Screen Shot 2020-06-30 at 1 34 39 PM" src="https://user-images.githubusercontent.com/1387940/86126573-73fdc500-bad6-11ea-8020-67aeaeaf9b23.png">

<img width="929" alt="Screen Shot 2020-06-30 at 1 48 35 PM" src="https://user-images.githubusercontent.com/1387940/86127837-72cd9780-bad8-11ea-8bd9-cb6cf8f0c821.png">

To reproduce:
- Create a protocol with a quick add name generator. Configure it with node of type person a 'name' variable, and a single prompt
- Add a second quick add name generator, and select the first node type.
- Then, click "change type". Accept the warning. Click "change type" again (why does it do this?).
- Crash.

**Comment by wwqrd** [comment] 2020-07-02 10:49
At the moment I can't reproduce this:
- There were a couple of prop warnings which I've now fixed,
- Have tried with the latest ui and the one in package.jon

**Comment by wwqrd** [comment] 2020-07-02 11:28
Updated reproduction steps:

- Create a protocol with a quick add name generator. Configure it with node of type person a 'name' variable, and a single prompt
- Save it
- Edit the original name generator, attempt to create a new node type
- Crash

**Comment by wwqrd** [comment] 2020-07-02 12:29
Resolved by #ebb9a0a9

**Closed by wwqrd** 2020-07-02 12:29 UTC
Labels: Architect, bug
