### ISSUE TITLE
Protocol format advanced/naive modes

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#38] opened 2018-04-23 09:57 UTC
Make the protocol project folder format an "advanced" feature, and default to opening saving as a zip (.netcanvas) file.

This could be added to the open dialog where the user could choose between .json and .netcanvas files.

**Comment by jthrilly** [comment] 2018-05-11 09:13
Duplicate of #45

**Closed by jthrilly** 2018-05-11 09:13 UTC
Labels: new feature, question
